### YamlMime:ManagedReference
items:
- uid: JBooth.MicroSplat.TextureArrayConfig.TextureChannel
  commentId: T:JBooth.MicroSplat.TextureArrayConfig.TextureChannel
  id: TextureArrayConfig.TextureChannel
  parent: JBooth.MicroSplat
  children:
  - JBooth.MicroSplat.TextureArrayConfig.TextureChannel.A
  - JBooth.MicroSplat.TextureArrayConfig.TextureChannel.B
  - JBooth.MicroSplat.TextureArrayConfig.TextureChannel.G
  - JBooth.MicroSplat.TextureArrayConfig.TextureChannel.R
  langs:
  - csharp
  - vb
  name: TextureArrayConfig.TextureChannel
  nameWithType: TextureArrayConfig.TextureChannel
  fullName: JBooth.MicroSplat.TextureArrayConfig.TextureChannel
  type: Enum
  source:
    id: TextureChannel
    path: B:\Games\Elavad\Assets\MicroSplat\Core\Scripts\TextureArrayConfig.cs
    startLine: 26
  assemblies:
  - Assembly-CSharp
  namespace: JBooth.MicroSplat
  syntax:
    content: public enum TextureChannel
    content.vb: Public Enum TextureChannel
  modifiers.csharp:
  - public
  - enum
  modifiers.vb:
  - Public
  - Enum
- uid: JBooth.MicroSplat.TextureArrayConfig.TextureChannel.R
  commentId: F:JBooth.MicroSplat.TextureArrayConfig.TextureChannel.R
  id: R
  parent: JBooth.MicroSplat.TextureArrayConfig.TextureChannel
  langs:
  - csharp
  - vb
  name: R
  nameWithType: TextureArrayConfig.TextureChannel.R
  fullName: JBooth.MicroSplat.TextureArrayConfig.TextureChannel.R
  type: Field
  source:
    id: R
    path: B:\Games\Elavad\Assets\MicroSplat\Core\Scripts\TextureArrayConfig.cs
    startLine: 28
  assemblies:
  - Assembly-CSharp
  namespace: JBooth.MicroSplat
  syntax:
    content: R = 0
    return:
      type: JBooth.MicroSplat.TextureArrayConfig.TextureChannel
  modifiers.csharp:
  - public
  - const
  modifiers.vb:
  - Public
  - Const
- uid: JBooth.MicroSplat.TextureArrayConfig.TextureChannel.G
  commentId: F:JBooth.MicroSplat.TextureArrayConfig.TextureChannel.G
  id: G
  parent: JBooth.MicroSplat.TextureArrayConfig.TextureChannel
  langs:
  - csharp
  - vb
  name: G
  nameWithType: TextureArrayConfig.TextureChannel.G
  fullName: JBooth.MicroSplat.TextureArrayConfig.TextureChannel.G
  type: Field
  source:
    id: G
    path: B:\Games\Elavad\Assets\MicroSplat\Core\Scripts\TextureArrayConfig.cs
    startLine: 29
  assemblies:
  - Assembly-CSharp
  namespace: JBooth.MicroSplat
  syntax:
    content: G = 1
    return:
      type: JBooth.MicroSplat.TextureArrayConfig.TextureChannel
  modifiers.csharp:
  - public
  - const
  modifiers.vb:
  - Public
  - Const
- uid: JBooth.MicroSplat.TextureArrayConfig.TextureChannel.B
  commentId: F:JBooth.MicroSplat.TextureArrayConfig.TextureChannel.B
  id: B
  parent: JBooth.MicroSplat.TextureArrayConfig.TextureChannel
  langs:
  - csharp
  - vb
  name: B
  nameWithType: TextureArrayConfig.TextureChannel.B
  fullName: JBooth.MicroSplat.TextureArrayConfig.TextureChannel.B
  type: Field
  source:
    id: B
    path: B:\Games\Elavad\Assets\MicroSplat\Core\Scripts\TextureArrayConfig.cs
    startLine: 30
  assemblies:
  - Assembly-CSharp
  namespace: JBooth.MicroSplat
  syntax:
    content: B = 2
    return:
      type: JBooth.MicroSplat.TextureArrayConfig.TextureChannel
  modifiers.csharp:
  - public
  - const
  modifiers.vb:
  - Public
  - Const
- uid: JBooth.MicroSplat.TextureArrayConfig.TextureChannel.A
  commentId: F:JBooth.MicroSplat.TextureArrayConfig.TextureChannel.A
  id: A
  parent: JBooth.MicroSplat.TextureArrayConfig.TextureChannel
  langs:
  - csharp
  - vb
  name: A
  nameWithType: TextureArrayConfig.TextureChannel.A
  fullName: JBooth.MicroSplat.TextureArrayConfig.TextureChannel.A
  type: Field
  source:
    id: A
    path: B:\Games\Elavad\Assets\MicroSplat\Core\Scripts\TextureArrayConfig.cs
    startLine: 31
  assemblies:
  - Assembly-CSharp
  namespace: JBooth.MicroSplat
  syntax:
    content: A = 3
    return:
      type: JBooth.MicroSplat.TextureArrayConfig.TextureChannel
  modifiers.csharp:
  - public
  - const
  modifiers.vb:
  - Public
  - Const
references:
- uid: JBooth.MicroSplat
  commentId: N:JBooth.MicroSplat
  name: JBooth.MicroSplat
  nameWithType: JBooth.MicroSplat
  fullName: JBooth.MicroSplat
- uid: JBooth.MicroSplat.TextureArrayConfig.TextureChannel
  commentId: T:JBooth.MicroSplat.TextureArrayConfig.TextureChannel
  parent: JBooth.MicroSplat
  name: TextureArrayConfig.TextureChannel
  nameWithType: TextureArrayConfig.TextureChannel
  fullName: JBooth.MicroSplat.TextureArrayConfig.TextureChannel
